### ISSUE TITLE
Network flexibility and efficiency issues

### ISSUE THREAD

**Issue by cuixing158** [matlab-deep-learning/Object-Detection-Using-YOLO-v2-Deep-Learning#1] opened 2020-05-01 02:21 UTC
I reproduced the original version of yolov3 / yolov4, but encountered the following problems:
1、The automatic differential derivation architecture is not fast (such as GIOU);
2、The network layer is not easy to control freely, and the location of the retrieval layer Very inefficient;
3、Network inference is much slower than the original framework (even with GPU).
yolov3-yolov4-matlab respository here: https://github.com/cuixing158/yolov3-yolov4-matlab

**I hope mathworks can strengthen the flexibility and efficiency of the above aspects** ,thankyou!

**Comment by davidwillingham** [comment] 2020-05-13 18:55
duplicate of another issue:
https://github.com/mathworks-robotics/deep-learning-for-object-detection-yolov2/issues/1

**Closed as completed by davidwillingham** 2020-05-13 18:55 UTC
